"""Generate the bundled g2408 fault/notification catalog from the app extract.

Transforms artifacts/g2408-plugin-extract/.../g2408_faults_localized.json into
custom_components/dreame_a2_mower/mower/data/fault_catalog.json — adding the
FAULT/ALERT/INFO `category` (fault_name prefix), a normalized `severity`, and
real newlines in detail text. Run with no args to (re)write the bundled file;
--check (dev-box, needs the artifact) compares without writing.
"""
from __future__ import annotations

import json
from pathlib import Path

TOOL_META = {
    "domain": "inventory",
    "run_by": "owner",
    "when": "When the g2408 plugin extract updates; regenerates the bundled fault catalog.",
    "summary": "Generate mower/data/fault_catalog.json (21-lang fault/notification strings) from the app extract.",
}

ARTIFACT = Path("/data/claude/homeassistant/artifacts/g2408-plugin-extract/tables/g2408_faults_localized.json")
OUT = Path(__file__).resolve().parents[2] / "custom_components/dreame_a2_mower/mower/data/fault_catalog.json"

_SEVERITY = {
    "异常": "anomaly", "故障": "malfunction",
    "工作消息": "work_message", "耗材消息": "consumable",
}


def _norm(s) -> str:
    return s.replace("\\n", "\n") if isinstance(s, str) else (s or "")


def build_catalog(localized: dict) -> dict:
    """Pure transform: extract JSON -> bundled catalog dict."""
    out: dict = {"meta": {
        "source": "g2408-plugin-extract ext1423 ver534 [apk:g2408-plugin-ext1423]",
        "source_file": "artifacts/g2408-plugin-extract/tables/g2408_faults_localized.json",
        "note": "GENERATED by tools/inventory/gen_fault_catalog.py — do not hand-edit",
    }}
    langs: set[str] = set()
    for channel in ("iot", "heartbeat"):
        ch = localized.get(channel) or {}
        out_ch: dict = {}
        for code, e in ch.items():
            fn = e.get("fault_name") or ""
            lang_out: dict = {}
            for lg, f in (e.get("lang") or {}).items():
                langs.add(lg)
                lang_out[lg] = {
                    "popup": f.get("popup") or "",
                    "alert": f.get("alert") or "",
                    "resident": f.get("resident") or "",
                    "detail_title": _norm(f.get("detailTitle")),
                    "detail": _norm(f.get("detail")),
                }
            out_ch[str(code)] = {
                "fault_name": fn,
                "category": fn.split("_")[0] if fn else "",
                "severity": _SEVERITY.get(e.get("messageType"), "unknown"),
                "can_suppress": bool(e.get("can_suppress")),
                "lang": lang_out,
            }
        out[channel] = out_ch
    out["meta"]["langs"] = sorted(langs)
    return out


def _render(catalog: dict) -> str:
    return json.dumps(catalog, sort_keys=True, ensure_ascii=False, indent=2) + "\n"


if __name__ == "__main__":  # pragma: no cover — CLI / dev I/O
    import argparse
    import sys

    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="compare regen vs committed (needs the artifact); no write")
    args = ap.parse_args()

    built = _render(build_catalog(json.loads(ARTIFACT.read_text(encoding="utf-8"))))
    if args.check:
        cur = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if cur != built:
            print("DRIFT: bundled fault_catalog.json != regen — run "
                  "tools/inventory/gen_fault_catalog.py", file=sys.stderr)
            sys.exit(1)
        print("ok: fault_catalog.json in sync")
        sys.exit(0)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(built, encoding="utf-8")
    print(f"wrote {OUT} ({len(built)} bytes)")
