"""Regenerate tools/README.md from each tool's TOOL_META.

An entry-point tool is any .py under tools/<domain>/ that declares a literal
TOOL_META dict, or any .sh with a `# tool-meta:` header. Helper/lib modules
(no TOOL_META) are skipped. The README is GENERATED — edit the tools, not it.

  python tools/gen_readme.py            # rewrite tools/README.md
  python tools/gen_readme.py --check    # exit 1 (with diff) if README is stale
"""
from __future__ import annotations

import argparse
import ast
import difflib
import sys
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
DOMAIN_ORDER = ["inventory", "probes", "state_machine", "session", "replay", "release"]
DOMAIN_BLURB = {
    "inventory": "Fact-discipline gates — keep inventory.yaml / entity-inventory.yaml / docs honest.",
    "probes": "Device & cloud probes for owner fact-finding. Some WRITE to the live mower.",
    "state_machine": "Entity-source / state-machine audit (run after coordinator or entity changes).",
    "session": "Reconstruct or verify session archives from probe logs (dev box).",
    "replay": "Corpus-replay golden harness — refactor-v2 safety net over months of real wire traffic.",
    "release": "Maintainer-only HACS publishing for this repo. Not general-purpose.",
}
RUN_BY_ICON = {"ci": "🤖 ci", "owner": "👤 owner", "maintainer": "🔧 maintainer"}


def _extract_py_meta(path: Path) -> dict | None:
    tree = ast.parse(path.read_text())
    for node in tree.body:
        if isinstance(node, ast.Assign) and any(
            isinstance(t, ast.Name) and t.id == "TOOL_META" for t in node.targets
        ):
            meta = ast.literal_eval(node.value)
            meta["path"] = str(path.relative_to(TOOLS_DIR.parent))
            meta["name"] = path.name
            return meta
    return None


def _extract_sh_meta(path: Path) -> dict | None:
    domain = run_by = when = summary = None
    for line in path.read_text().splitlines():
        s = line.strip()
        if s.startswith("# tool-meta:"):
            for kv in s.removeprefix("# tool-meta:").split():
                k, _, v = kv.partition("=")
                if k == "domain":
                    domain = v
                elif k == "run_by":
                    run_by = v
        elif s.startswith("# tool-when:"):
            when = s.removeprefix("# tool-when:").strip()
        elif s.startswith("# tool-summary:"):
            summary = s.removeprefix("# tool-summary:").strip()
    if domain and run_by:
        return {"domain": domain, "run_by": run_by, "when": when or "",
                "summary": summary or "", "path": str(path.relative_to(TOOLS_DIR.parent)),
                "name": path.name}
    return None


def scan_tools(tools_dir: Path) -> list[dict]:
    out: list[dict] = []
    for path in sorted(tools_dir.rglob("*.py")):
        if path.name in ("gen_readme.py", "_toolmeta.py") or "__pycache__" in path.parts or path.name.startswith("._"):
            continue
        meta = _extract_py_meta(path)
        if meta:
            out.append(meta)
    for path in sorted(tools_dir.rglob("*.sh")):
        meta = _extract_sh_meta(path)
        if meta:
            out.append(meta)
    return out


def _invocation(meta: dict) -> str:
    if meta["name"].endswith(".sh"):
        return f"`{meta['path']}`"
    return f"`python {meta['path']}`"


def render(tools: list[dict]) -> str:
    lines = [
        "# tools/",
        "",
        "<!-- GENERATED by tools/gen_readme.py — do not hand-edit. "
        "Run `python tools/gen_readme.py` after changing a tool's TOOL_META. -->",
        "",
        "Helper scripts for this integration, grouped by domain. Each tool also "
        "prints its domain/run-by/when on `--help`.",
        "",
        "**Run by:** 🤖 `ci` runs automatically in CI (you rarely invoke by hand) · "
        "👤 `owner` you run for debugging/fact-finding · 🔧 `maintainer` repo-specific.",
        "",
    ]
    by_domain: dict[str, list[dict]] = {d: [] for d in DOMAIN_ORDER}
    for t in tools:
        by_domain.setdefault(t["domain"], []).append(t)
    for domain in DOMAIN_ORDER:
        items = sorted(by_domain.get(domain, []), key=lambda m: m["name"])
        if not items:
            continue
        lines += [f"## `{domain}/`", "", DOMAIN_BLURB.get(domain, ""), ""]
        for m in items:
            lines += [
                f"### {_invocation(m)}  —  {RUN_BY_ICON[m['run_by']]}",
                "",
                m["summary"],
                "",
                f"*When:* {m['when']}",
                "",
            ]
    lines += [
        "---",
        "",
        "Historical one-off migrations & recovery tools live in "
        "`OLD/ha-dreame-a2-mower-tools/` (out of the working tree).",
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 with a diff if README.md is stale")
    args = ap.parse_args(argv)
    readme = TOOLS_DIR / "README.md"
    new = render(scan_tools(TOOLS_DIR))
    if args.check:
        old = readme.read_text() if readme.exists() else ""
        if old != new:
            sys.stdout.writelines(difflib.unified_diff(
                old.splitlines(True), new.splitlines(True),
                fromfile="README.md (committed)", tofile="README.md (generated)"))
            return 1
        return 0
    readme.write_text(new)
    print(f"wrote {readme}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
